import { Router, Request, Response } from 'express';
import { prisma } from '../index.js';

const router = Router();

// GET /api/export/report/:id/json - Get full report data as JSON
router.get('/report/:id/json', async (req: Request, res: Response) => {
  try {
    const report = await prisma.report.findUnique({
      where: { id: Number(req.params.id) },
      include: { analysisResult: true },
    });
    if (!report) return res.status(404).json({ error: 'Report not found' });

    res.json(report);
  } catch (err) {
    res.status(500).json({ error: 'Export failed' });
  }
});

// GET /api/export/report/:id/text - Get plain text report summary
router.get('/report/:id/text', async (req: Request, res: Response) => {
  try {
    const report = await prisma.report.findUnique({
      where: { id: Number(req.params.id) },
      include: { analysisResult: true },
    });
    if (!report) return res.status(404).json({ error: 'Report not found' });

    const analysisData = report.analysisResult?.resultData
      ? JSON.parse(report.analysisResult.resultData)
      : null;

    let text = `========================================\n`;
    text += `  SHIELDPLAN ENGINEERING REPORT\n`;
    text += `========================================\n\n`;
    text += `Title: ${report.title}\n`;
    text += `Status: ${report.status}\n`;
    text += `Date: ${new Date(report.createdAt).toLocaleString()}\n`;
    if (report.modalityName) text += `Modality: ${report.modalityName}\n`;
    if (report.machineModel) text += `Machine: ${report.machineModel}\n`;
    if (report.roomType) text += `Room Type: ${report.roomType}\n`;
    if (report.facilityType) text += `Facility: ${report.facilityType}\n`;
    text += `\n`;

    if (report.summary) {
      text += `--- Summary ---\n${report.summary}\n\n`;
    }

    if (analysisData) {
      if (analysisData.annualDose !== undefined) {
        text += `--- Results ---\n`;
        text += `Max Annual Dose: ${analysisData.annualDose} mSv/yr\n`;
        text += `Compliance Score: ${analysisData.complianceScore || 'N/A'}\n`;
        text += `Status: ${analysisData.status || 'N/A'}\n`;
        text += `\n`;
      }

      if (analysisData.wallDetails) {
        text += `--- Per-Wall Analysis ---\n`;
        analysisData.wallDetails.forEach((w: any) => {
          text += `${w.wall}: ${w.material} ${w.thickness}cm | Annual: ${w.annualDose} mSv/yr | ${w.isSafe ? 'SAFE' : 'REQUIRES ATTENTION'}\n`;
        });
        text += `\n`;
      }

      if (analysisData.recommendations && analysisData.recommendations.length > 0) {
        text += `--- Recommendations ---\n`;
        analysisData.recommendations.forEach((r: string, i: number) => {
          text += `${i + 1}. ${r}\n`;
        });
        text += `\n`;
      }
    }

    text += `========================================\n`;
    text += `  Generated by SHIELDPLAN AI\n`;
    text += `========================================\n`;

    res.setHeader('Content-Type', 'text/plain');
    res.setHeader('Content-Disposition', `attachment; filename="shieldplan-report-${report.id}.txt"`);
    res.send(text);
  } catch (err) {
    res.status(500).json({ error: 'Export failed' });
  }
});

// POST /api/export/report/:id/markdown - Generate markdown report
router.get('/report/:id/markdown', async (req: Request, res: Response) => {
  try {
    const report = await prisma.report.findUnique({
      where: { id: Number(req.params.id) },
      include: { analysisResult: true },
    });
    if (!report) return res.status(404).json({ error: 'Report not found' });

    const analysisData = report.analysisResult?.resultData
      ? JSON.parse(report.analysisResult.resultData)
      : null;

    let md = `# SHIELDPLAN Engineering Report\n\n`;
    md += `**Title:** ${report.title}  \n`;
    md += `**Status:** ${report.status}  \n`;
    md += `**Date:** ${new Date(report.createdAt).toLocaleString()}  \n`;
    if (report.modalityName) md += `**Modality:** ${report.modalityName}  \n`;
    if (report.machineModel) md += `**Machine:** ${report.machineModel}  \n`;
    if (report.roomType) md += `**Room Type:** ${report.roomType}  \n`;
    if (report.facilityType) md += `**Facility:** ${report.facilityType}  \n`;
    md += `\n---\n\n`;

    if (report.summary) {
      md += `## Summary\n\n${report.summary}\n\n---\n\n`;
    }

    if (analysisData) {
      if (analysisData.annualDose !== undefined) {
        md += `## Results\n\n`;
        md += `| Parameter | Value |\n`;
        md += `|-----------|-------|\n`;
        md += `| Max Annual Dose | ${analysisData.annualDose} mSv/yr |\n`;
        md += `| Compliance Score | ${analysisData.complianceScore || 'N/A'} |\n`;
        md += `| Status | ${analysisData.status || 'N/A'} |\n`;
        md += `\n`;
      }

      if (analysisData.wallDetails) {
        md += `## Per-Wall Analysis\n\n`;
        md += `| Wall | Material | Thickness | Annual Dose | Status |\n`;
        md += `|------|----------|-----------|-------------|--------|\n`;
        analysisData.wallDetails.forEach((w: any) => {
          md += `| ${w.wall} | ${w.material} | ${w.thickness} cm | ${w.annualDose} mSv/yr | ${w.isSafe ? '✅ SAFE' : '⚠️ REVIEW'} |\n`;
        });
        md += `\n`;
      }

      if (analysisData.recommendations && analysisData.recommendations.length > 0) {
        md += `## Recommendations\n\n`;
        analysisData.recommendations.forEach((r: string) => {
          md += `- ${r}\n`;
        });
        md += `\n`;
      }
    }

    md += `---\n\n*Generated by SHIELDPLAN AI*`;

    res.setHeader('Content-Type', 'text/markdown');
    res.setHeader('Content-Disposition', `attachment; filename="shieldplan-report-${report.id}.md"`);
    res.send(md);
  } catch (err) {
    res.status(500).json({ error: 'Export failed' });
  }
});

export default router;
